---
# https://github.com/anthropics/claude-code
- name: Install Claude Code
  shell: curl -fsSL https://claude.ai/install.sh | bash
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/claude"

# https://github.com/openai/codex
- name: Install Codex
  shell: curl -fsSL https://chatgpt.com/codex/install.sh | sh
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/codex"

# https://ollama.com/download
- name: Install Ollama
  shell: curl -fsSL https://ollama.com/install.sh | sh
  args:
    creates: /usr/local/bin/ollama

# https://github.com/upstash/context7
- name: Install ctx7 CLI
  shell: |
    export NVM_DIR="${HOME}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    npm install -g ctx7
  args:
    executable: /bin/bash
