#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.5"
model_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_verbosity = "high"
hide_agent_reasoning = false
show_raw_agent_reasoning = true
approval_policy = "on-request"
personality = "pragmatic"
sandbox_mode = "workspace-write"
web_search = "live"

[analytics]
enabled = false

[history]
persistence = "save-all"

[sandbox_workspace_write]
network_access = true
writable_roots = [
    "/Users/vinta/.codex/skills",
    "/Users/vinta/Projects",
    "/usr/local/hal-9000",
]

[features]
shell_snapshot = true
unified_exec = true
multi_agent = true
memories = true

[tools]
view_image = true
web_search = { context_size = "high" }

[feedback]
enabled = false

[otel]
exporter = "none"
metrics_exporter = "none"
trace_exporter = "none"

[tui]
notifications = ["agent-turn-complete", "approval-requested"]
notification_condition = "unfocused"
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-remaining", "codex-version"]

[tui.model_availability_nux]
"gpt-5.3-codex-spark" = 3
"gpt-5.5" = 4

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.openaiDeveloperDocs.tools.search_openai_docs]
approval_mode = "approve"

[mcp_servers.openaiDeveloperDocs.tools.fetch_openai_doc]
approval_mode = "approve"

[projects."/usr/local/hal-9000"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/awesome-python"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/catianway"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/dear-ai"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/laughing-man"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/mensab"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/of-course-i-still-love-you"]
trust_level = "trusted"

[projects."/Users/vinta/Projects/finance"]
trust_level = "trusted"
