---
- name: Ensure HAL environment is sourced in .zshrc
  lineinfile:
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    line: "source {{ REPO_ROOT }}/playbooks/roles/hal/files/hal_profile.sh"
    state: present
  when: ansible_facts["env"]["SHELL"] == "/bin/zsh"
