---
# https://github.com/astral-sh/uv
- name: Install uv
  shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/uv"

- name: Upgrade uv
  shell: |
    export PATH="$HOME/.local/bin:$PATH"
    uv self update
  args:
    executable: /bin/bash
  register: python_uv_self_update
  changed_when: "'already on version' not in python_uv_self_update.stderr"

# https://www.python.org/downloads/
- name: Install Python 3.14.6
  shell: |
    export PATH="$HOME/.local/bin:$PATH"
    uv python install 3.14.6
    uv python pin 3.14.6 --global
  args:
    executable: /bin/bash
  register: python_uv_install
  changed_when: "'Installed' in python_uv_install.stderr"

- name: Create global python symlinks
  shell: |
    export PATH="$HOME/.local/bin:$PATH"
    mkdir -p {{ ansible_facts['env']['HOME'] }}/.local/bin
    ln -sf $(uv python find --system) {{ ansible_facts['env']['HOME'] }}/.local/bin/python
    ln -sf $(uv python find --system) {{ ansible_facts['env']['HOME'] }}/.local/bin/python3
  args:
    executable: /bin/bash
  changed_when: false

- name: Ensure Python environment is sourced in .zshrc
  lineinfile:
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    line: "source {{ REPO_ROOT }}/playbooks/roles/python/files/py_profile.sh"
    state: present
  when: ansible_facts["env"]["SHELL"] == "/bin/zsh"
