---
# https://go.dev/doc/devel/release
- name: Install Go 1.26
  homebrew:
    name:
      - go@1.26
    state: latest

- name: Link Go 1.26 as the default go
  homebrew:
    name:
      - go@1.26
    state: linked
    install_options: force

- name: Ensure Go environment is sourced in .zshrc
  lineinfile:
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    line: "source {{ REPO_ROOT }}/playbooks/roles/go/files/go_profile.sh"
    state: present
  when: ansible_facts["env"]["SHELL"] == "/bin/zsh"
