#!/usr/bin/env python3
# Compiles cspell word lists into aspell dictionaries so Claude Code's `spellcheck` setting stops
# underlining ordinary programming vocabulary.
#
# Claude Code spawns aspell with a hardcoded argv (`-a --encoding=utf-8 --sug-mode=ultra`), so extra
# dictionaries can only reach it through `~/.aspell.conf`, which aspell reads unaided. That file is
# written straight to the home directory rather than kept in `dotfiles/`: it is derived entirely from
# `DICTIONARIES` below, and its paths have to be absolute because aspell resolves anything else
# against dict-dir rather than home-dir, so committing it would version a machine-specific path.
#
# The hand-curated personal dictionary is a separate layer: `dotfiles/.aspell.en.pws`, symlinked to
# `~/.aspell.en.pws`. This script never touches it.

import json
import re
import subprocess
import sys
from pathlib import Path

# Pinned so a regeneration months from now produces the same dictionaries. Bump deliberately.
CSPELL_REF = "2b8901c77a68c31c65decf17cca4a81b3e96cc07"  # pragma: allowlist secret
CSPELL_REPO = "streetsidesoftware/cspell-dicts"

# Folder names under https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries
# Add more here as needed. Never add `en-common-misspellings` — it is a list of misspellings, and
# compiling it would teach aspell to accept typos.
DICTIONARIES = ("software-terms", "aws", "companies", "cryptocurrencies", "google", "node", "npm", "python", "typescript")

ASPELL_LANG = "en"
ASPELL_DICT_DIR = Path.home() / ".aspell"
ASPELL_CONF = Path.home() / ".aspell.conf"

# Entries are lower-cased before compiling: aspell accepts the capitalised form of a lower-case entry
# but not the reverse, so `figma` covers both `figma` and `Figma` while cspell's own `Figma` covers
# only the latter. That also folds `GitLab` and `BigQuery` into the lower-case forms actually typed.
# Non-alphabetic entries stay out because Claude Code's tokenizer never sends them. The floor is 2
# because that is the shortest word it does send, and of the two-letter entries these lists add, only
# `na`, `os` and `pu` transpose a common English word.
MIN_WORD_LENGTH = 2
MAX_WORD_LENGTH = 64
APOSTROPHES = ("'", "\u2019")


def reaches_aspell(word: str) -> bool:
    if not MIN_WORD_LENGTH <= len(word) <= MAX_WORD_LENGTH:
        return False
    core = word
    for apostrophe in APOSTROPHES:
        core = core.replace(apostrophe, "")
    return core.isalpha()


# Python's urllib cannot reach GitHub from inside the agent sandbox, and curl is a hard dependency of
# the playbooks anyway
def fetch(url: str) -> str:
    result = subprocess.run(  # noqa: S603 subprocess-without-shell-equals-true
        ["curl", "-fsSL", url],  # noqa: S607 start-process-with-partial-path
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        message = f"failed to fetch {url}: {result.stderr.strip() or f'curl exit {result.returncode}'}"
        raise SystemExit(message)
    return result.stdout


def word_list_urls(dictionary: str) -> list[str]:
    listing = json.loads(fetch(f"https://api.github.com/repos/{CSPELL_REPO}/contents/dictionaries/{dictionary}/dict?ref={CSPELL_REF}"))
    return sorted(entry["download_url"] for entry in listing if entry["name"].endswith(".txt"))


def words_from(url: str) -> set[str]:
    words = set()
    for raw_line in fetch(url).splitlines():
        line = raw_line.strip()
        # `#` comments cspell's build directives, `!` marks a word as forbidden rather than allowed
        if not line or line.startswith(("#", "!")):
            continue
        # cspell marks compoundable affixes with `*`, `+` and `~`
        word = re.sub(r"^[*+~]+|[*+~]+$", "", line).lower()
        if reaches_aspell(word):
            words.add(word)
    return words


def compile_dictionary(dictionary: str) -> Path:
    words: set[str] = set()
    for url in word_list_urls(dictionary):
        words |= words_from(url)
    if not words:
        message = f"{dictionary}: no usable words found"
        raise SystemExit(message)

    destination = ASPELL_DICT_DIR / f"{dictionary}.rws"
    subprocess.run(  # noqa: S603 subprocess-without-shell-equals-true
        ["aspell", "--lang", ASPELL_LANG, "create", "master", str(destination)],  # noqa: S607 start-process-with-partial-path
        input="\n".join(sorted(words)) + "\n",
        text=True,
        check=True,
    )
    print(f"{dictionary}: {len(words)} words -> {destination}")
    return destination


def main() -> None:
    ASPELL_DICT_DIR.mkdir(parents=True, exist_ok=True)
    compiled = [compile_dictionary(dictionary) for dictionary in DICTIONARIES]

    lines = [
        "# Generated by scripts/generate-aspell-dicts.py - edits are overwritten.",
        "# Paths must be absolute: aspell resolves anything else against dict-dir, not home-dir.",
        *(f"add-extra-dicts {path}" for path in compiled),
    ]
    ASPELL_CONF.write_text("\n".join(lines) + "\n")
    print(f"wrote {ASPELL_CONF}")
    print("Restart Claude Code to pick this up - the checker process reads its dictionaries once, at startup.")


if __name__ == "__main__":
    sys.exit(main())
