---
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: Install awscli
  shell: curl -fsSL https://awscli.amazonaws.com/v2/install.sh | sudo bash -s -- --system
  args:
    creates: /usr/local/bin/aws

# https://github.com/weaveworks/eksctl/blob/main/README.md#installation
- name: Download eksctl
  shell: sh -c 'curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_$(arch).tar.gz" | tar xz -C /tmp'
  args:
    creates: /usr/local/bin/eksctl

- name: Install eksctl
  command: sudo mv /tmp/eksctl /usr/local/bin
  args:
    creates: /usr/local/bin/eksctl
