---
- name: Install prerequisite packages
  homebrew:
    name:
      - coreutils
      - fzf
      - gnu-tar
      - jq
    state: latest

# https://kubernetes.io/releases/
# https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/
- name: Install kubectl
  shell: |
    ARCH=$(uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/')
    curl -sLo /tmp/kubectl "https://dl.k8s.io/release/v1.35.6/bin/darwin/${ARCH}/kubectl"
    sudo install -m 0755 -o root -g wheel /tmp/kubectl /usr/local/bin && rm /tmp/kubectl
  args:
    creates: /usr/local/bin/kubectl

# https://github.com/derailed/k9s
- name: Install k9s
  homebrew:
    name:
      - derailed/k9s/k9s
    state: latest

- name: Ensure Kubernetes environment is sourced in .zshrc
  lineinfile:
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    line: "source {{ REPO_ROOT }}/playbooks/roles/kubernetes/files/k8s_profile.sh"
    state: present
  when: ansible_facts["env"]["SHELL"] == "/bin/zsh"
