---
# https://kubernetes.io/releases/
# https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/
- name: Install kubectl
  shell: |
    ARCH=$(uname -m | sed 's/x86_64/amd64/' | sed 's/aarch64/arm64/')
    curl -sLo /tmp/kubectl "https://dl.k8s.io/release/v1.35.6/bin/darwin/${ARCH}/kubectl"
    mkdir -p "$HOME/.local/bin"
    install -m 0755 /tmp/kubectl "$HOME/.local/bin" && rm /tmp/kubectl
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/kubectl"

- name: Tap derailed/k9s
  homebrew_tap:
    name:
      - derailed/k9s

# https://github.com/derailed/k9s
- name: Install k9s
  homebrew:
    name:
      - derailed/k9s/k9s
    state: latest

- name: Ensure Kubernetes environment is sourced in .zshrc
  lineinfile:
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    line: "source {{ REPO_ROOT }}/playbooks/roles/kubernetes/files/k8s_profile.sh"
    state: present
  when: ansible_facts["env"]["SHELL"] == "/bin/zsh"
